require('configs.cmp')
require('configs.lsp')
require("nnn").setup()
require('nvim-web-devicons').setup({ default = true; })
require('configs.lualine')
require('configs.treesitter')
require('configs.telescope')
require('Comment').setup()
require("nvim-autopairs").setup()
require('go').setup()
require('configs.rust')
require('gitsigns').setup()
require('configs.neogit')
require"fidget".setup{}
